---
# handlers file for tomcat

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart tomcat instance
  ansible.builtin.service:
    name: "{{ instance_name }}"
    state: restarted
  when:
    - not ansible_check_mode
