---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no
  strategy: free

  roles:
    - role: ansible-role-tomcat
      tomcat_layout:
        - name: tomcat
        - name: tomcat7
          directory: /opt/tomcat7
          version: 7
          user: tomcat7
          group: tomcat7
          xms: 512M
          xmx: 1024M
          non_ssl_connector_port: 8081
          ssl_connector_port: 8444
          shutdown_port: 8006
          ajp_port: 8010
          wars:
            - url: https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/sample.war
        - name: tomcat8
          directory: /opt/tomcat8
          version: 8
          user: tomcat8
          group: tomcat8
          xms: 512M
          xmx: 1024M
          non_ssl_connector_port: 8082
          ssl_connector_port: 8445
          shutdown_port: 8007
          ajp_port: 8011
        - name: tomcat9
          directory: /opt/tomcat9
          version: 9
          user: tomcat9
          group: tomcat9
          xms: 512M
          xmx: 1024M
          non_ssl_connector_port: 8083
          ssl_connector_port: 8446
          shutdown_port: 8008
          ajp_port: 8012
        - name: tomcat-large
          directory: /opt/tomcat-large
          xms: 1024M
          xmx: 2048M
          non_ssl_connector_port: 8084
          ssl_connector_port: 8447
          shutdown_port: 9008
          ajp_port: 9012
